### ISSUE TITLE
章雪

### ISSUE THREAD

**Issue by zhangxuejunior** [SocratesClub/bigdata#10]
<h1> 自我介绍</h1>
<h2>基本情况</h2>
<table>
  <tr align=center>
     <td style="font-size:15px"><b>姓名</b></td>
     <td style="font-size:15px"><b>学号</b></td>
     <td style="font-size:15px"><b>院系</b></td>
     <td style="font-size:15px"><b>专业</b></td>
     <td style="font-size:15px"><b>年级</b></td>
     <td style="font-size:15px"><b>导师</b></td>
   </tr>
   <tr>
     <td style="font-size:15px">章雪</td>
     <td style="font-size:15px">MG1715043</td>
     <td style="font-size:15px">工程管理学院</td>
     <td style="font-size:15px">管理科学与工程</td>
     <td style="font-size:15px">2017</td>
     <td style="font-size:15px">沈厚才</td>
   </tr>
</table>
<hr>
<ul>
   <li><b>个人主页：</b><a href="https://github.com/zhangxuejunior">https://github.com/zhangxuejunior</a></li>
	<li><b>邮箱：</b>zhangxuejw@163.com</li>
</ul>

**Comment by zhangxuejunior** [comment]
[MG1715043-章雪-第二次作业.html.zip](https://github.com/computational-class/bigdata/files/1850272/MG1715043-.-.html.zip)

**Comment by zhangxuejunior** [comment]
[MG1715043-章雪-第三次作业.zip](https://github.com/computational-class/bigdata/files/1892599/MG1715043-.-.zip)

**Comment by zhangxuejunior** [comment]
[MG1715043-章雪-第四次作业.zip](https://github.com/computational-class/bigdata/files/1947037/MG1715043-.-.zip)

**Comment by zhangxuejunior** [comment]
[MG1715043_章雪_第六次作业.zip](https://github.com/computational-class/bigdata/files/2068354/MG1715043_._.zip)

**Comment by zhangxuejunior** [comment]
[MG1715043-章雪-第八次作业.zip](https://github.com/computational-class/bigdata/files/2195547/MG1715043-.-.zip)

**Comment by zhangxuejunior** [comment]
[MG1715043-章雪-第七次作业.zip](https://github.com/computational-class/bigdata/files/2195850/MG1715043-.-.zip)

**Comment by zhangxuejunior** [comment]
[MG1715043-章雪-期末作业.zip](https://github.com/computational-class/bigdata/files/2195851/MG1715043-.-.zip)

**Comment by Xiaochengzi2048** [comment]
第五次作业是否忘记上传啦？
