### ISSUE TITLE
沙心悦

### ISSUE THREAD

**Issue by XinyueSha** [SocratesClub/bigdata#12]
<h1>自我介绍</h1>
<h2>基本情况</h2>
<table>
 <tr >  
        <td>姓名</td>
         <td>学号</td>
         <td>年级</td>
         <td>院系</td>
         <td>专业</td>
  </tr>
<tr >  
        <td>沙心悦</td>
         <td>MG1711027</td>
         <td>2017级</td>
         <td>新闻传播学院</td>
         <td>传播学</td>
</tr>
</table>

<ul>
   <li> <b>个人主页:</b><a href="https://github.com/XinyueSha">https://github.com/XinyueSha</a>
   </li>
  <li> <b>个人邮箱:</b><a >shaxinyue30110@163.com</a>
   </li>

</ul>
<h2></h2>
<img src="https://octodex.github.com/images/filmtocat.png"  />

**Comment by XinyueSha** [comment]
[沙心悦 第二次作业  MG1711027.htm.zip](https://github.com/computational-class/bigdata/files/1847503/MG1711027.htm.zip)

**Comment by XinyueSha** [comment]
[MG1711027  沙心悦.html.zip](https://github.com/computational-class/bigdata/files/1847523/MG1711027.html.zip)

**Comment by XinyueSha** [comment]
[MG1711027 沙心悦 第二次作业.html.zip](https://github.com/computational-class/bigdata/files/1847554/MG1711027.html.zip)

**Comment by XinyueSha** [comment]
[MG1711027 沙心悦 第二次作业.html.zip](https://github.com/computational-class/bigdata/files/1847562/MG1711027.html.zip)

**Comment by XinyueSha** [comment]
[沙心悦 MG1711027 第三次作业.html.zip](https://github.com/computational-class/bigdata/files/1888627/MG1711027.html.zip)

**Comment by XinyueSha** [comment]
[沙心悦 MG1711027 第四次作业 .html.zip](https://github.com/computational-class/bigdata/files/1938477/MG1711027.html.zip)

**Comment by XinyueSha** [comment]
/Users/shaxinyue/Desktop/MG1711027 沙心悦 第五次作业.htm.zip

**Comment by XinyueSha** [comment]
[MG1711027 沙心悦 第五次作业.htm.zip](https://github.com/computational-class/bigdata/files/2195790/MG1711027.htm.zip)

**Comment by XinyueSha** [comment]
[MG1711027 沙心悦 期末作业.html.zip](https://github.com/computational-class/bigdata/files/2195793/MG1711027.html.zip)

**Comment by Xiaochengzi2048** [comment]
还差三次平时作业，请核对是否忘记提交啦？
