### ISSUE TITLE
魏晓惠

### ISSUE THREAD

**Issue by Lahui** [SocratesClub/bigdata#13]
姓名：魏晓惠  
年级：2017级
专业：新闻与传播 
学号： MP1711024   
联系方式
邮箱：weixiaohui1994@163.com

不会做表格，不会删除线~~~~
在这儿写下这些信息的过程也是懵B的~
悲桑到呕吐。。。。

**Comment by Xiaoquer950612** [comment]
魏晓惠 MP1711024 第二次作业
[MP1711024魏晓惠.zip](https://github.com/computational-class/bigdata/files/1848697/MP1711024.zip)

**Comment by Xiaoquer950612** [comment]
[魏晓惠 第三次作业 抓取豆瓣top250电影.zip](https://github.com/computational-class/bigdata/files/1886453/top250.zip)

**Comment by Lahui** [comment]
[MP1711024.zip](https://github.com/computational-class/bigdata/files/1940801/MP1711024.zip)

**Comment by Lahui** [comment]
[MP1711024  转发网络 魏晓惠.zip](https://github.com/computational-class/bigdata/files/1940802/MP1711024.zip)

**Comment by Lahui** [comment]
[魏晓惠 第六次作业.zip](https://github.com/computational-class/bigdata/files/2070902/default.zip)

**Comment by Lahui** [comment]
[MP1711024  魏晓惠  第七次作业.zip](https://github.com/computational-class/bigdata/files/2180377/MP1711024.zip)

**Comment by Lahui** [comment]
[MP1711024  魏晓惠  期末个人大作业.zip](https://github.com/computational-class/bigdata/files/2180382/MP1711024.zip)

**Comment by Xiaochengzi2048** [comment]
请核对是否忘记上传两次平时作业？

**Comment by Xiaoquer950612** [comment]
[魏晓惠第五次作业 政府工作报告.zip](https://github.com/computational-class/bigdata/files/2197191/default.zip)

**Comment by Xiaoquer950612** [comment]
[魏晓惠第八次作业.zip](https://github.com/computational-class/bigdata/files/2197193/default.zip)
