### ISSUE TITLE
学生分组和签到信息

### ISSUE THREAD

**Issue by chengjun** [SocratesClub/bigdata#138]
1. 吴悦文 周尚谕 史诗艺 盛玉婕
	- 数据抓取 part 1
2. 王东丽MG1811010 黄薇MF1811015 聂若玲MF1811029 陈虹MP1811001
	- 数据抓取 part 2
3. 吴友钦 MG1811028 李心仪 MG1811017 刘若衡 MG1811020 苏浩然 MG1806066
	- 数据清洗 part 1
4. MG1814022 张旭 MG1814012 南霞 MF1811013 胡娜 MF1811012 郭玉波
	- 数据清洗 part 2
5. MF1811040 童浩 MF1811046 王帅 MF1811049 王瑜显 戴秋伊
	- 统计分析 参考[Data Science from Scratch](https://github.com/computational-class/datascience2018/tree/gh-pages/3.scratch/code-python3)
6. 朱惠 MG1811039 王晶晶 MF1811043 陈小丽 MG1811012 <del>温雅钧 MF1811052</del>
	- 机器学习 part 1 参考[Python data science handbook chapter 5](https://github.com/computational-class/datascience2018/tree/gh-pages/4.datasci/notebooks) 
7. 钱明雅MF1811032 荣聪MF1811033 魏颖MF1811051 
	- 机器学习 part 2 参考[Python data science handbook chapter 5](https://github.com/computational-class/datascience2018/tree/gh-pages/4.datasci/notebooks) 
8. 王艳 MF1811048 李桐辰 MF1811021 杨佳奕 MG1811032 徐绘敏 MG1811031
	- 文本挖掘 part 1
9. 朱小东MF1811074 杨 懿MF1811061 张 群 MF1811066 张 瑾 MF1811065
	- 文本挖掘 part 2
10. <del>MF1811039 田园</del> MF1811062 姚祎婷 MF1811059 许祎琦 MF1811069 赵晶
	- 推荐系统
11. 尹迪 MF1811063 张冠生 MF1811064 韩雪 MP1811005 陈冠合 MF1811003
	- 网络科学 part 1
12. 匡宇扬 MG1814009 赵思雨 MG1814024 谭旸 MG1814015 刘琪琪 MG1814010
	- 网络科学 part 2
13. 李让 MG1836012  史婉霜  MF1811034 钟洁 MG1823082
        - 可视化

**Comment by Katherine1116** [comment]
匡宇扬 MG1814009
赵思雨 MG1814024
谭旸     MG1814015
刘琪琪 MG1814010

**Comment by fredyd00987** [comment]
小组成员：
尹迪 MF1811063
张冠生 MF1811064
韩雪 MP1811005
陈冠合 MF1811003

**Comment by yyyyyhbg** [comment]
MF1811039 田园
MF1811062 姚祎婷
MF1811059 许祎琦
MF1811069 赵晶

**Comment by Julieyang17** [comment]
朱小东MF1811074
杨 懿MF1811061
张 群 MF1811066
张 瑾 MF1811065

**Comment by wwwww-99** [comment]
小组成员！
王艳 MF1811048
李桐辰 MF1811021
杨佳奕 MG1811032
徐绘敏 MG1811031

**Comment by KatherineRong** [comment]
钱明雅MF1811032 荣聪MF1811033 魏颖MF1811051

**Comment by YvonneZHH** [comment]
朱惠 MG1811039
王晶晶 MF1811043
陈小丽 MG1811012
温雅钧 MF1811052

**Comment by pre-tonghao** [comment]
MF1811040 童浩
MF1811046  王帅
MF1811049   王瑜显
MF1811068  张一哲

**Comment by Hxuxu** [comment]
小组成员：
MG1814022 张旭
MG1814012 南霞
MF1811013 胡娜
MF1811012 郭玉波

**Comment by Floranceliu** [comment]
吴友钦 MG1811028
李心仪 MG1811017
刘若衡 MG1811020
苏浩然 MG1806066

**Comment by MaodeeNie** [comment]
王东丽MG1811010 黄薇MF1811015 聂若玲MF1811029 陈虹MP1811001

**Comment by sabrinawuu** [comment]
吴悦文 周尚谕 史诗艺

**Comment by Jade-sheng** [comment]
盛玉婕
戴秋伊
张一哲

**Comment by chengjun** [comment]
![2019第一次签到](https://user-images.githubusercontent.com/543384/54501250-1edc8500-495f-11e9-8d91-23c88fd6a900.jpeg)

第一次签到
