### ISSUE TITLE
聂思宇

### ISSUE THREAD

**Issue by yuuuuuuuu1996** [SocratesClub/bigdata#18]
# 自我介绍
> ### 基本信息
* 姓名：**聂思宇**
* 手机：**17626043976**
* 邮箱：<niesiyu@smail.nju.edu.cn>
* 个人主页：<https://yuuuuuuuu1996.github.io>
* * *
> ### 校园信息
| 学号 | 院系 | 专业 | 年级 |
| - | - | - | - |
| MG1711025 | 新闻传播学院 | 传播学 | 2017级 |
* * *
> ### 个人标签
 ` 90后 `    ` 南京大学 `   ` 研究僧 `   
* * *
> ### 个人签名
    If not now,when? If not me,who?
    若非此时，何时？若非是我，何人？
* * *
> ### 个人自拍
![自拍](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1520824528654&di=64d2c7c1fc253796e658d570bd2e8af2&imgtype=0&src=http%3A%2F%2Fimg.pconline.com.cn%2Fimages%2Fupload%2Fupc%2Ftx%2Fpcdlc%2F1701%2F07%2Fc6%2F34984677_1483786600547.gif)

**Comment by yuuuuuuuu1996** [comment]
[第二次作业.html.zip](https://github.com/computational-class/bigdata/files/1829904/html.zip)

**Comment by yuuuuuuuu1996** [comment]
[第三次作业.html.zip](https://github.com/computational-class/bigdata/files/1880888/html.zip)

**Comment by yuuuuuuuu1996** [comment]
[第四次作业.html.zip](https://github.com/computational-class/bigdata/files/1937433/html.zip)

**Comment by yuuuuuuuu1996** [comment]
[第六次作业.html.zip](https://github.com/computational-class/bigdata/files/2070933/html.zip)

**Comment by yuuuuuuuu1996** [comment]
[第五次作业.html.zip](https://github.com/computational-class/bigdata/files/2072140/html.zip)

**Comment by yuuuuuuuu1996** [comment]
[第七次作业.html.zip](https://github.com/computational-class/bigdata/files/2113926/html.zip)

**Comment by yuuuuuuuu1996** [comment]
[第八次作业.html.zip](https://github.com/computational-class/bigdata/files/2117496/html.zip)

**Comment by Xiaochengzi2048** [comment]
大作业未及时提交?
