### ISSUE TITLE
第十二组小组作业：网络科学

### ISSUE THREAD

**Issue by njukikiL** [SocratesClub/bigdata#182]
[MG1814010-刘琪琪-网络科学使用NetworkX分析复杂网络-小组作业.zip](https://github.com/computational-class/bigdata/files/3389395/MG1814010-.-.NetworkX.-.zip)

**Comment by Zhaosy5** [comment]
[MG1814024-赵思雨-12组小组展示（EoN：使用Python模拟网络中的疾病传播模型）.zip](https://github.com/computational-class/bigdata/files/3389442/MG1814024-.-12.EoN.Python.zip)

**Comment by Katherine1116** [comment]
[MG1814009_匡宇扬_network_analysis_of_tianya_bbs.zip](https://github.com/computational-class/bigdata/files/3389743/MG1814009_._network_analysis_of_tianya_bbs.zip)

**Comment by drjenny** [comment]
[MG1814015 谭旸 EoN模拟和可视化.zip](https://github.com/computational-class/bigdata/files/3394981/MG1814015.EoN.zip)
