### ISSUE TITLE
刘俊俊

### ISSUE THREAD

**Issue by Rebacca-Liu** [SocratesClub/bigdata#19]
# <div align = center>**刘俊俊** </div> <div align = center>:bowtie:LIU JunJun:bowtie: </div>

## 基本信息：
学号 | 学院 | 专业 | 年级
------------ | -------------| -------------| -------------
&nbsp;&nbsp;&nbsp;&nbsp;MG1715024&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;工程管理学院&nbsp;&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;&nbsp; 管理科学与工程&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;2017级研究生&nbsp;&nbsp;&nbsp;&nbsp;

## 联系方式
*<div align =center>:house:  https://github.com/Rebacca-Liu* &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :e-mail: <liujunjun1217@126.com> </div>

## 课程期望
 希望大家
* 一起进步
* 学好本领
* 走上巅峰
<div align = center>然后的然后......................................................为中华民族伟大复兴奋斗( •̀ ω •́ )，耶:v::joy::joy:</div>
&nbsp;
&nbsp;
&nbsp;

![](https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2935847596,1085477571&fm=27&gp=0.jpg)

**Comment by ruofuzero** [comment]
**队长的目标果然宏伟**

**Comment by Rebacca-Liu** [comment]
[刘俊俊第二次作业.zip](https://github.com/computational-class/bigdata/files/1850255/default.zip)

**Comment by Rebacca-Liu** [comment]
[刘俊俊第三次作业-爬虫：豆瓣电影top250.zip](https://github.com/computational-class/bigdata/files/1887126/-.top250.zip)

**Comment by Rebacca-Liu** [comment]
[刘俊俊第四次作业：转发网络提取.zip](https://github.com/computational-class/bigdata/files/1938821/default.zip)

**Comment by Rebacca-Liu** [comment]
[MG1715024-刘俊俊-第六次作业.zip](https://github.com/computational-class/bigdata/files/2075813/MG1715024-.-.zip)

**Comment by Rebacca-Liu** [comment]
[MG1715025+刘俊俊+第五次作业.zip](https://github.com/computational-class/bigdata/files/2093299/MG1715025.zip)

**Comment by Rebacca-Liu** [comment]
[MG1715024+刘俊俊+第七次作业.zip](https://github.com/computational-class/bigdata/files/2114268/MG1715024.zip)

**Comment by Rebacca-Liu** [comment]
[MG1715024+刘俊俊+第八次作业.zip](https://github.com/computational-class/bigdata/files/2140482/MG1715024.zip)

**Comment by Rebacca-Liu** [comment]
[个人大作业-刘俊俊.zip](https://github.com/computational-class/bigdata/files/2195870/-.zip)
