### ISSUE TITLE
刘畅之

### ISSUE THREAD

**Issue by guesswhaaat** [SocratesClub/bigdata#2]
# 🥇 自我介绍
<br>

|**姓名**|**学号**|**专业**|**年级**|
|:---:|:---:|:---:|:---:|
|刘畅之|MG1611030|传播学|2016级|

-----
### **个人网站**
- ```Github个人主页 ``` : <https://guesswhaaat.github.io/>(刚建的…)

### **邮箱**
- ```Personal Email``` : <lczwalk@qq.com>
- ```Academic Email``` : <mg1611030@smail.nju.edu.cn>

### **图片是本人**
<img src="https://i.loli.net/2018/03/08/5aa0fd5edb6ba.jpg" width="50%" height="50%">

<br>

>还有啥可介（practice）绍（markdown）呢......
>>👍 ~[特朗普的发型](https://www.mirror.co.uk/news/weird-news/secret-behind-trumps-hair-finally-9755063)很棒~ 👍 
>>（我只是想试试看~删除线~和[链接](http://www.google.cn/)）

**Comment by Lahui** [comment]
删除线，厉害了

**Comment by guesswhaaat** [comment]
[Round2.zip](https://github.com/computational-class/bigdata/files/1847733/Round2.zip)

（有一个 没做出来  报错 查懵了 真实的不知道怎么办

**Comment by guesswhaaat** [comment]
[捉住豆瓣TOP250.zip](https://github.com/computational-class/bigdata/files/1888320/TOP250.zip)

（Windows用户没办法下载为md文件，各种把文件检测为病毒自动删除，怎么调设置都没用，只能html保存了）

**Comment by guesswhaaat** [comment]
[刘畅之 第四次作业-转发网络.zip](https://github.com/computational-class/bigdata/files/1938873/-.zip)

**Comment by guesswhaaat** [comment]
[MG1611030 刘畅之 第六次作业.zip](https://github.com/computational-class/bigdata/files/2180123/MG1611030.zip)

**Comment by guesswhaaat** [comment]
[MG1611030 刘畅之 第五次作业 政府工作报告文本挖掘.zip](https://github.com/computational-class/bigdata/files/2159466/MG1611030.zip)

**Comment by guesswhaaat** [comment]
[MG1611030 刘畅之 第七次作业.zip](https://github.com/computational-class/bigdata/files/2170211/MG1611030.zip)

**Comment by guesswhaaat** [comment]
[MG1611030 刘畅之 第八次作业.zip](https://github.com/computational-class/bigdata/files/2173454/MG1611030.zip)

**Comment by guesswhaaat** [comment]
[MG1611030 刘畅之 期末作业：OWS推特数挖.zip](https://github.com/computational-class/bigdata/files/2195520/MG1611030.OWS.zip)
