### ISSUE TITLE
董丹丹

### ISSUE THREAD

**Issue by EstelaMaggie** [SocratesClub/bigdata#21]
*Welcome to **_My Label_***

## 基本信息
专业 | 姓名 | 学号 | 年级
------------ | ------------- | ------------- | -------------
传播学 | 董丹丹 | MG1711015 | 2017级

##### 个人网页
https://github.com/EstelaMaggie
##### 个人邮箱
dongdandan9899@163.com

## THE END~
![e298a3aa8a162a9433dd64dbff432212](https://user-images.githubusercontent.com/37280911/37271694-e625f35a-260e-11e8-9346-1333049097d8.png)

**Comment by EstelaMaggie** [comment]
[董丹丹MG1711015.zip](https://github.com/computational-class/bigdata/files/1841585/MG1711015.zip)

**Comment by EstelaMaggie** [comment]
[董丹丹MG1711015.html.zip](https://github.com/computational-class/bigdata/files/1888208/MG1711015.html.zip)

**Comment by EstelaMaggie** [comment]
[董丹丹MG1711015.html.zip](https://github.com/computational-class/bigdata/files/1939344/MG1711015.html.zip)

**Comment by EstelaMaggie** [comment]
[董丹丹MG1711015.zip](https://github.com/computational-class/bigdata/files/2068053/MG1711015.zip)

**Comment by EstelaMaggie** [comment]
[董丹丹-MG1711015.zip](https://github.com/computational-class/bigdata/files/2092769/-MG1711015.zip)

**Comment by EstelaMaggie** [comment]
[董丹丹MG1711015.zip](https://github.com/computational-class/bigdata/files/2111000/MG1711015.zip)

**Comment by EstelaMaggie** [comment]
[期末大作业-董丹丹-MG1711015.zip](https://github.com/computational-class/bigdata/files/2195650/-.-MG1711015.zip)

**Comment by EstelaMaggie** [comment]
[期末大作业-董丹丹-MG1711015.zip](https://github.com/computational-class/bigdata/files/2195651/-.-MG1711015.zip)

**Comment by Xiaochengzi2048** [comment]
平时作业少一次，请核对是否忘记上传啦？

**Comment by EstelaMaggie** [comment]
马上核对，感谢提醒




| |
董丹丹
邮箱：dongdandan9899@163.com
|

签名由 网易邮箱大师 定制

在2018年07月16日 15:25，Mystica Zhang 写道：

平时作业少一次，请核对是否忘记上传啦？

**Comment by EstelaMaggie** [comment]
[董丹丹-MG1711015.html.zip](https://github.com/computational-class/bigdata/files/2196805/-MG1711015.html.zip)

**Comment by EstelaMaggie** [comment]
你好，缺少的一份平时作业已上传，十分感谢🌹




| |
董丹丹
邮箱：dongdandan9899@163.com
|

签名由 网易邮箱大师 定制

在2018年07月16日 15:26，董丹丹 写道：
马上核对，感谢提醒




| |
董丹丹
邮箱：dongdandan9899@163.com
|

签名由 网易邮箱大师 定制

在2018年07月16日 15:25，Mystica Zhang 写道：

平时作业少一次，请核对是否忘记上传啦？
