### ISSUE TITLE
魏立杰

### ISSUE THREAD

**Issue by CactusPatrick** [SocratesClub/bigdata#28]
# 个人介绍
## 基本信息
姓名 | 学号 | 院系 | 专业
------------ | ------------- | ------------- | -------------
魏立杰 | MF1711026 | 新闻传播学院 | 新闻与传播
## 联系方式
* 个人主页：[魏立杰的GitHub主页](https://github.com/CactusPatrick)
* 邮箱：piewlj@163.com

**Comment by CactusPatrick** [comment]
[魏立杰 MF1711026 第二次作业.zip](https://github.com/computational-class/bigdata/files/1848926/MF1711026.zip)

**Comment by CactusPatrick** [comment]
[魏立杰 MF1711026 第三次作业.zip](https://github.com/computational-class/bigdata/files/1892955/MF1711026.zip)

**Comment by CactusPatrick** [comment]
[魏立杰 MF1711026第四次作业.zip](https://github.com/computational-class/bigdata/files/2098545/MF1711026.zip)

**Comment by CactusPatrick** [comment]
[魏立杰 MF1711026第六次作业.zip](https://github.com/computational-class/bigdata/files/2098547/MF1711026.zip)

**Comment by CactusPatrick** [comment]
[魏立杰 MF1711026第五次作业.zip](https://github.com/computational-class/bigdata/files/2098550/MF1711026.zip)

**Comment by Xiaochengzi2048** [comment]
还差最后两次小作业和个人大作业，请核对是否忘记提交？
