### ISSUE TITLE
林启帆

### ISSUE THREAD

**Issue by Lelouch211** [SocratesClub/bigdata#29]
# 个人信息
姓名：林启帆
学号：MG1713004
院系：国际关系研究院 国际关系专业

# 联系方式
个人邮箱:mg1713004@smail.nju.edu.cn
个人主页：https://github.com/Lelouch211

**Comment by Lelouch211** [comment]
王老师，不知道为什么我用Spyder保存HTML格式只能保存一部分，而不能把所有程序都包含进来，所以我把它拆成几部分了。
[Uploading 第二次作业MG1713004.zip…]()
[Uploading 第二次作业MG1713004.zip…]()

**Comment by Lelouch211** [comment]
王老师，不知道为什么我用Spyder保存HTML格式只能保存一部分，而不能把所有程序都包含进来，所以我把它拆成几部分了。
[第二次作业MG1713004.zip](https://github.com/computational-class/bigdata/files/1850213/MG1713004.zip)

**Comment by Lelouch211** [comment]
[MG1713004l林启帆第三次作业.zip](https://github.com/computational-class/bigdata/files/1892826/MG1713004l.zip)
亲爱的王老师，这是第三次作业

**Comment by Lelouch211** [comment]
[MG1713004林启帆第四次作业.zip](https://github.com/computational-class/bigdata/files/1940880/MG1713004.zip)
亲爱的王老师，这是第四次作业，中间还有不少困惑的地方。

**Comment by Lelouch211** [comment]
[林启帆第五次作业.zip](https://github.com/computational-class/bigdata/files/2070876/default.zip)
第五次作业

**Comment by Lelouch211** [comment]
[MG1713004 林启帆 第六次作业.zip](https://github.com/computational-class/bigdata/files/2092595/MG1713004.zip)

**Comment by Lelouch211** [comment]
[林启帆第六次作业.zip](https://github.com/computational-class/bigdata/files/2113866/default.zip)
中间弄不出来

**Comment by Xiaochengzi2048** [comment]
还差一次小作业和最后的final大作业，请核对是否忘记提交？

**Comment by Lelouch211** [comment]
@MYSTICA1994 抱歉，之前去华中师大参加夏令营事太多一是忙不过来，拖到十四五号才想起赶工，这是最后一次小作业，最后的大作业还剩最后一小部分，今天之内一定一定会传上来，抱歉抱歉，真的特别对不起。
[MG1713004 7次作业.zip](https://github.com/computational-class/bigdata/files/2206569/MG1713004.7.zip)

**Comment by Lelouch211** [comment]
@MYSTICA1994 抱歉，晚了三天才交，甚是惭愧，向王老师道歉，向负责同学道歉，希望还来得及
[MG1713004 林启帆期末大数据作业.zip](https://github.com/computational-class/bigdata/files/2208978/MG1713004.zip)

**Comment by Lelouch211** [comment]
@MYSTICA1994 对于迟交了3天的事儿真的万分抱歉，给王老师和您这位负责的同学带来了太多的麻烦，在此向您与王老师真挚的道歉，感谢同学你的提醒，望王老师工作顺利，望同学您学业工作都一帆风顺，祝好。
[MG1713004 林启帆 期末大数据作业.zip](https://github.com/computational-class/bigdata/files/2209091/MG1713004.zip)

**Comment by Lelouch211** [comment]
@MYSTICA1994 另外，我想重交之前有部分没弄出来的第六次作业（情感分析），请问可以吗？感谢
[MG1713004 重交第六次作业情感分析.zip](https://github.com/computational-class/bigdata/files/2209227/MG1713004.zip)

**Comment by Xiaochengzi2048** [comment]
好的收到！假期快乐！
