### ISSUE TITLE
吴丹

### ISSUE THREAD

**Issue by damersolo** [SocratesClub/bigdata#3]
# 自我介绍
***
## 个人信息
| 姓名  | 学号  | 学院 | 专业  |
| :-------: | :------: | :------:| :-----: |
| 吴丹 | MG1715035 | 工程管理学院 | 管理科学与工程| 

## 个人网站
- **GitHub主页**：[*我的主页*](https://github.com/damersolo)
- **GitHub头像**：（练习图链）
![我的头像](https://avatars2.githubusercontent.com/u/37126290?s=460&v=4)

## Markdown其他练习
~~很开心这里支持emoji~~ :full_moon_with_face:   
>I am not crazy, my mother had me tested.

**Comment by damersolo** [comment]
[homework02.zip](https://github.com/computational-class/bigdata/files/1848052/homework02.zip)

第二次作业

quotes_historical_yahoo_ochl那一条调不出来，查了很多还是不会改

**Comment by damersolo** [comment]
第三次作业
根据04.PythonCrawler_beautifulsoup.ipynb中的相关代码抓取top250豆瓣电影的名称、URL、得分、评价数。

[homework03.zip](https://github.com/computational-class/bigdata/files/1889866/homework03.zip)

**Comment by damersolo** [comment]
第四次作业
采用分段读取的策略对数据进行处理，提取其转发网络

[作业4.zip](https://github.com/computational-class/bigdata/files/1935568/4.zip)

**Comment by damersolo** [comment]
第六次作业 机器学习部分
采用cross validation的方法对泰坦尼克号数据中的算法、超级参数、变量进行选择，并对测试集数据进行预测。

[作业6 机器学习部分.zip](https://github.com/computational-class/bigdata/files/2066745/6.zip)

**Comment by damersolo** [comment]
[作业5 吴丹.zip](https://github.com/computational-class/bigdata/files/2087753/5.zip)

第五次作业
政府工作报告文本挖掘，分词、词云、时间序列三个部分

**Comment by damersolo** [comment]
[作业6 情感分析部分.zip](https://github.com/computational-class/bigdata/files/2110234/6.zip)

第七次作业（第六次作业的情感分析部分）
1： 使用另外一种sklearn的分类器来对tweet_negative2进行情感分析
2： 使用https://github.com/victorneo/Twitter-Sentimental-Analysis 所提供的推特数据进行情感分析，可以使用其代码 https://github.com/victorneo/Twitter-Sentimental-Analysis/blob/master/classification.py

**Comment by damersolo** [comment]
[作业7 吴丹.zip](https://github.com/computational-class/bigdata/files/2115926/7.zip)

第八次作业 主题模型
使用graphlab进行主题模型分析

**Comment by damersolo** [comment]
[期末大作业 吴丹.zip](https://github.com/computational-class/bigdata/files/2188828/default.zip)
期末大作业

**Comment by Xiaochengzi2048** [comment]
请核对第八次作业是否忘记上传啦？

**Comment by damersolo** [comment]
@MYSTICA1994 
你好，我一共交了八份平时作业+一份大作业，序号是按照老师的作业wiki给的，里面有两个“作业6”，但是内容不一样（分别是机器学习和情感分析），我已经在交作业的评论里补充说明了，麻烦你再看一下，谢谢！

**Comment by Xiaochengzi2048** [comment]
好的！已收到！是我没仔细看评论，抱歉！~
