### ISSUE TITLE
张蕖

### ISSUE THREAD

**Issue by Xiaoquer950612** [SocratesClub/bigdata#30]
学号 MP1711035
姓名 张蕖
专业 新闻与传播

**Comment by Xiaoquer950612** [comment]
[张蕖大数据.zip](https://github.com/computational-class/bigdata/files/1850768/default.zip)

**Comment by Xiaoquer950612** [comment]
[Uploading 张蕖豆瓣.zip…]()

**Comment by Xiaoquer950612** [comment]
[张蕖豆瓣250.zip](https://github.com/computational-class/bigdata/files/1892950/250.zip)

**Comment by Xiaoquer950612** [comment]
[MP1711035 张蕖.zip](https://github.com/computational-class/bigdata/files/1942015/MP1711035.zip)

**Comment by Xiaochengzi2048** [comment]
还有四次小作业和最后的个人大作业未提交，请核对~

**Comment by Xiaoquer950612** [comment]
[张蕖第五次作业 政府工作报告.zip](https://github.com/computational-class/bigdata/files/2196945/default.zip)

**Comment by Xiaoquer950612** [comment]
[张蕖第六次作业.zip](https://github.com/computational-class/bigdata/files/2196959/default.zip)

**Comment by Xiaoquer950612** [comment]
[张蕖第七次作业.zip](https://github.com/computational-class/bigdata/files/2197066/default.zip)

**Comment by Xiaoquer950612** [comment]
[张蕖第八次作业.zip](https://github.com/computational-class/bigdata/files/2197167/default.zip)

**Comment by Xiaochengzi2048** [comment]
好的收到~
