### ISSUE TITLE
仲志源

### ISSUE THREAD

**Issue by ozzyk123** [SocratesClub/bigdata#34]
### **基本信息** 
姓名：仲志源
学号：MP1702120
学院：经济学院
联系方式
邮箱：786547252@qq.com
个人网页：https://github.com/ozzyk123

**Comment by ozzyk123** [comment]
[第二次作业-仲志源-MG1702120 1.zip](https://github.com/computational-class/bigdata/files/1848418/-.-MG1702120.1.zip)

**Comment by ozzyk123** [comment]
[第三次作业-仲志源-MG1702120.zip](https://github.com/computational-class/bigdata/files/1887142/-.-MG1702120.zip)

**Comment by ozzyk123** [comment]
[第四次作业-仲志源-MG1702120.zip](https://github.com/computational-class/bigdata/files/1937100/-.-MG1702120.zip)

**Comment by ozzyk123** [comment]
[仲志源-第六次作业.zip](https://github.com/computational-class/bigdata/files/2068248/-.zip)

**Comment by ozzyk123** [comment]
[第五次作业 仲志源 MG1702120.zip](https://github.com/computational-class/bigdata/files/2093010/MG1702120.zip)

**Comment by ozzyk123** [comment]
[第七次作业 仲志源 MG1702120.zip](https://github.com/computational-class/bigdata/files/2114273/MG1702120.zip)

**Comment by ozzyk123** [comment]
[期末大作业-仲志源-MG1702120.zip](https://github.com/computational-class/bigdata/files/2192607/-.-MG1702120.zip)

**Comment by Xiaochengzi2048** [comment]
请核对第八次作业是否忘记上传啦？
