### ISSUE TITLE
张晓雨

### ISSUE THREAD

**Issue by Xiaochengzi2048** [SocratesClub/bigdata#36]
姓名 张晓雨
学号 MF1711037
学院 新闻传播学院
联系方式 17621618096
邮箱 mystica0809@foxmail.com

**Comment by Xiaochengzi2048** [comment]
[TheSecondTest-MF1711037-张晓雨 .zip](https://github.com/computational-class/bigdata/files/1847168/TheSecondTest-MF1711037-.zip)

**Comment by MysticaZhang** [comment]
[Douban-Zhangxiaoyu.zip](https://github.com/computational-class/bigdata/files/1923171/Douban-Zhangxiaoyu.zip)

**Comment by MysticaZhang** [comment]
[第四次作业_张晓雨.html.zip](https://github.com/computational-class/bigdata/files/1940867/_.html.zip)


The package twitter_text couldn't work, I'll try it again later~

**Comment by MysticaZhang** [comment]
[TheFifthAssignment-MF1711037-Zhangxiaoyu.html.zip](https://github.com/computational-class/bigdata/files/2172637/TheFifthAssignment-MF1711037-Zhangxiaoyu.html.zip)

**Comment by MysticaZhang** [comment]
[第六次作业-MF1711037-张晓雨.ipynb.zip](https://github.com/computational-class/bigdata/files/2172680/-MF1711037-.ipynb.zip)

**Comment by MysticaZhang** [comment]
[第6-2次作业-MF1711037-张晓雨.ipynb.zip](https://github.com/computational-class/bigdata/files/2172710/6-2.-MF1711037-.ipynb.zip)

**Comment by MysticaZhang** [comment]
[第八次作业-MF1711037-张晓雨.html.zip](https://github.com/computational-class/bigdata/files/2173843/-MF1711037-.html.zip)

**Comment by MysticaZhang** [comment]
[Flights delay analysis - MF1711037 - 张晓雨.zip](https://github.com/computational-class/bigdata/files/2194618/Flights.delay.analysis.-.MF1711037.-.zip)
FinalProject1

**Comment by MysticaZhang** [comment]
[ows-analysis-MF1711037-张晓雨.html.zip](https://github.com/computational-class/bigdata/files/2195464/ows-analysis-MF1711037-.html.zip)
FinalProject2 OWS-related
