### ISSUE TITLE
刘晓艺

### ISSUE THREAD

**Issue by Xiaoyi-Liu** [SocratesClub/bigdata#4]
学号：MG1711022

**Comment by Xiaoyi-Liu** [comment]
[the 1st assignment by 刘晓艺.zip](https://github.com/computational-class/bigdata/files/1850094/the.1st.assignment.by.zip)

**Comment by Xiaoyi-Liu** [comment]
[抓取豆瓣电影 Top 250作业 -刘晓艺.zip](https://github.com/computational-class/bigdata/files/1887671/Top.250.-.zip)

**Comment by Xiaoyi-Liu** [comment]
[tweets 转发网络 - 刘晓艺.zip](https://github.com/computational-class/bigdata/files/1937526/tweets.-.zip)

**Comment by Xiaoyi-Liu** [comment]
[刘晓艺第六次作业.zip](https://github.com/computational-class/bigdata/files/2070415/default.zip)

**Comment by Xiaoyi-Liu** [comment]
[刘晓艺第五次作业.zip](https://github.com/computational-class/bigdata/files/2092557/default.zip)

**Comment by Xiaoyi-Liu** [comment]
[刘晓艺第七次作业.zip](https://github.com/computational-class/bigdata/files/2194804/default.zip)

**Comment by Xiaoyi-Liu** [comment]
[刘晓艺第七次作业_.zip](https://github.com/computational-class/bigdata/files/2194948/_.zip)

**Comment by Xiaoyi-Liu** [comment]
[刘晓艺期末作业.zip](https://github.com/computational-class/bigdata/files/2195042/default.zip)

**Comment by Xiaochengzi2048** [comment]
请核对第八次作业是否忘记上传啦？

**Comment by Xiaoyi-Liu** [comment]
十分感谢提醒！看了下确实漏掉了这个，我今天晚上回去就上传！




20:07分 已传！谢谢！
[刘晓艺第八次作业.zip](https://github.com/computational-class/bigdata/files/2197492/default.zip)




在2018年07月16日 15:28 ，Mystica Zhang<mailto:notifications@github.com>写道：


请核对第八次作业是否忘记上传啦？
