### ISSUE TITLE
陆轶倩

### ISSUE THREAD

**Issue by lu-yi-qian** [SocratesClub/bigdata#40]
### 基本信息

|  姓名  |   学号    |   专业   |  年级  |
| :----: | :-------: | :------: | :----: |
| 陆轶倩 | MF1711013 | 新闻传播 | 2017级 |

### 联系方式

* 邮箱：luyiqian2014@163.com

**Comment by lu-yi-qian** [comment]
[MF1711013.zip](https://github.com/computational-class/bigdata/files/1938581/MF1711013.zip)
第二次作业

**Comment by lu-yi-qian** [comment]
[第三次作业 陆轶倩 MF1711013.zip](https://github.com/computational-class/bigdata/files/1938588/MF1711013.zip)
第三次作业

**Comment by lu-yi-qian** [comment]
[第四次作业 陆轶倩 MF1711013.zip](https://github.com/computational-class/bigdata/files/1938596/MF1711013.zip)
第四次作业

**Comment by LUYIQIAN** [comment]
[第五次作业 陆轶倩 MF1711013.zip](https://github.com/computational-class/bigdata/files/2090668/MF1711013.zip)

**Comment by LUYIQIAN** [comment]
[第六次作业 陆轶倩 MF1711013.zip](https://github.com/computational-class/bigdata/files/2090670/MF1711013.zip)

**Comment by LUYIQIAN** [comment]
[期末 陆轶倩 MF1711013.zip](https://github.com/computational-class/bigdata/files/2195778/MF1711013.zip)

**Comment by Xiaochengzi2048** [comment]
还差两次平时作业，请核对一下是否忘记上传啦？
