### ISSUE TITLE
徐梦云

### ISSUE THREAD

**Issue by pilgriming** [SocratesClub/bigdata#5]
徐梦云 MP1711028

**Comment by pilgriming** [comment]
徐梦云第二次作业
[Untitled6.zip](https://github.com/computational-class/bigdata/files/1885976/Untitled6.zip)

**Comment by Xiaoquer950612** [comment]
[徐梦云 第三次作业.zip](https://github.com/computational-class/bigdata/files/1893081/default.zip)

**Comment by Lahui** [comment]
[MP17110248 转发网络 徐梦云.zip](https://github.com/computational-class/bigdata/files/1940804/MP17110248.zip)

**Comment by Lahui** [comment]
[MP1711028 转发网络 徐梦云.zip](https://github.com/computational-class/bigdata/files/1940805/MP1711028.zip)

**Comment by Lahui** [comment]
[第六次作业 机器学习   徐梦云.zip](https://github.com/computational-class/bigdata/files/2071035/default.zip)

**Comment by Lahui** [comment]
[MP1711028 徐梦云 期末作业.zip](https://github.com/computational-class/bigdata/files/2195787/MP1711028.zip)

**Comment by Xiaochengzi2048** [comment]
还差三次平时作业？

**Comment by Xiaoquer950612** [comment]
[徐梦云第五次作业 政府工作报告.zip](https://github.com/computational-class/bigdata/files/2197175/default.zip)

**Comment by Xiaoquer950612** [comment]
[徐梦云第七次作业.zip](https://github.com/computational-class/bigdata/files/2197178/default.zip)

**Comment by Xiaoquer950612** [comment]
[徐梦云第八次作业.zip](https://github.com/computational-class/bigdata/files/2197181/default.zip)
